version: '3'
services:
    forex-fun:
        build: ./forex-fun
        environment:
            - NODE_ENV=production
        ports:
            - '4200:4200'
        depends_on:
            - forex-node
        #working_dir: /forex/forex-fun
        #volumes:
           #- ./forex-fun:/forex/forex-fun:cached
    
    forex-node:
        build: ./forex-node
        environment:
            - NODE_ENV=production
            - PORT=3000
        ports:
            - '3000:3000'
        #working_dir: /forex/forex-node
        #volumes:
            #- ./forex-node:/forex/forex-node:cached
